# _config.yml
title: "Public Study"
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
  hard_wrap: false

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
